Feature/#28 add option to use with existing project
valantic/spartacus-mock pull request #29
Opened 2023-06-19 12:50 UTC by janwidmer

2023-08-18 11:22 UTC, claudio147 requested changes

2023-08-18 11:22 UTC, claudio147 commented on projects/spartacus-mock/src/lib/handlers/base-handler.ts
> +import { titleList } from '../mock-data';
Could we combine them in a single import?

2023-08-18 11:22 UTC, claudio147 commented on projects/spartacus-mock/src/lib/handlers/account-handler.ts
> +import { createConsentTemplate } from '../mock-data';
Could we combine them in a single import?

2023-08-18 11:22 UTC, claudio147 commented on projects/spartacus-mock/src/lib/handlers/product-handler.ts
> +import { productSearchPage } from '../mock-data';
Could we combine them in a single import?

2023-08-18 11:22 UTC, claudio147 commented on projects/spartacus-mock/src/lib/handlers/user-handler.ts
> +import { createUser } from '../mock-data';
Could we combine them in a single import?

2023-08-18 11:22 UTC, claudio147 commented on projects/spartacus-mock/src/lib/mock-data/account/product-interests.ts
> +import { createSort } from '../general';
Could we combine them in a single import?

2023-08-23 12:42 UTC, janwidmer commented on projects/spartacus-mock/src/lib/mock-data/account/product-interests.ts
> +import { createSort } from '../general';
done

2023-08-23 12:42 UTC, janwidmer commented on projects/spartacus-mock/src/lib/handlers/account-handler.ts
> +import { createConsentTemplate } from '../mock-data';
done

2023-08-23 12:43 UTC, janwidmer commented on projects/spartacus-mock/src/lib/handlers/product-handler.ts
> +import { productSearchPage } from '../mock-data';
done

2023-08-23 12:52 UTC, claudio147 approved these changes

2023-08-23 12:53 UTC, merged